services:
  - type: web
    name: queueos-backend
    env: node
    rootDir: queueOS-backend
    buildCommand: npm install && npx prisma db push
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: REDIS_URL
        sync: false
      - key: REDIS_HOST
        sync: false
      - key: REDIS_PORT
        sync: false
      - key: REDIS_PASSWORD
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: NODE_ENV
        value: production
